use_frameworks!

target 'ConcentricProgressRingView_Example' do
  pod 'ConcentricProgressRingView', :path => '../'
  pod 'LionheartExtensions', '~> 3.4'

  target 'ConcentricProgressRingView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
