use_frameworks!
platform :ios, '10.3'

target 'ConcentricProgressRingView_Example' do
  pod 'ConcentricProgressRingView', :path => '../'
  pod 'LionheartExtensions', '~> 3.4'

  target 'ConcentricProgressRingView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1'
    pod 'Nimble', '~> 7.0'
  end
end
